baseURL = "https://jaigansa.github.io/truckshop/"
copyright = "© Truckshop"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Asia/Kolkata"
timeout = "120s"
title = "TruckShop"
theme = 'gallery'

[params]
  defaultTheme = "dark"
  description = "Our Works Showcase and Details"
  title = "TruckShop"
  [params.author]
    email = "jaigansa@gmail.com"
    name = "Jai Ganesh"
  [params.socialIcons]
    facebook = "https://www.facebook.com/srijaiganeshindustry"
    instagram = "https://www.instagram.com/jaigansa"
    youtube = "https://www.youtube.com/@jsrindustries"
    email = "mailto:jaisriramtruckshop@gmail.com"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"


[menu]
  [[menu.footer]]
    name = "Map"
    url = "https://google.com"
    weight = 3

[services]
  [services.rss]
    limit = 100

[related]
  includeNewer = false